### ISSUE TITLE
「ハンズオン環境および講義資料のインストール」に関して

### ISSUE THREAD

**Issue by atayino** [chemo-wakate/tutorial-7th#10]
首記の件で質問です。

①リポジトリのクローンについて
> git clone https://github.com/chemo-wakate/tutorial-6th.git
↑上記を実行するように、とのご指示ですが、今回は第七回ということで、↓が正しいのではないでしょうか？
> git clone https://github.com/chemo-wakate/tutorial-7th.git

②インストールの確認、について
①のいずれの場合も実施してみたところ、フォルダ("chemo"と"work")は表示されますが、Notebookは表示されませんでした。

対処法があれば、教えて頂けますでしょうか？

**Comment by yamasakih** [comment]
@ayino 様

>①リポジトリのクローンについて

おっしゃるとおり7thの方を`git clone`してください。
失礼しました。訂正しておきます。

>②インストールの確認、について
>①のいずれの場合も実施してみたところ、フォルダ("chemo"と"work")は表示されますが、Notebookは表示されませんでした。

確認させてください。
`sh ./run_jupyter.sh` を実行したがJupyter Notebookが起動しなかった。
ということでよろしいでしょうか？

**Comment by atayino** [comment]
> 確認させてください。
> sh ./run_jupyter.sh を実行したがJupyter Notebookが起動しなかった。
> ということでよろしいでしょうか？

dockerにてsh ./run_jupyter.shを実行したところ、Jupyter Notebookは起動し、指定されたアドレスを入力することでJupyterのHomeにはアクセスできました。
ただ、フォルダのリストは表示されていますが、Notebookなどのファイルは見えませんでした。
("The notebook list is empty"と出ています)

**Comment by yamasakih** [comment]
@ayino 様

コメントありがとうございます。

それでしたら無事Docker環境は構築できていそうですね。
おそらくJupyter Notebookをまだフォルダに入れる以前のリポジトリを
`git clone`してきているのだと思います。

現在、教材は推敲を重ねている途中ですので入門講座当日無線LANが利用なパソコンでしたら
当日にリポジトリを最新のものにしていただければ結構だと思います。
(おそらく他の方にもお願いすると思います)

もし今すぐに確認したいようでしたら
`git clone`で作成された`tutorial-7th`フォルダの中で
```
git fetch
git checkout master
git pull origin master
```
を順次行っていただいた後、再度`sh ./run_jupyter.sh`すれば
数個Jupyter Notebookのファイルがadvancedフォルダの中に入っているのを確認できると思います。

いかがでしょうか？

**Comment by atayino** [comment]
ご指示の通りやってみましたが、同じ結果でした。やはりフォルダ名のみ表示されています。
※自分のローカルフォルダには"Cross-validation.ipynb"や"RandomForest.ipynb"がダウンロードされているようですので、少なくとも当日講義を受ける際の支障はなさそうです。

**Comment by yamasakih** [comment]
@ayino 様

コメントありがとうございます。

>※自分のローカルフォルダには"Cross-validation.ipynb"や"RandomForest.ipynb"がダウンロードされているようですので、少なくとも当日講義を受ける際の支障はなさそうです。

この様子でしたら`git clone`はうまくいっているようですね。よかったです。

Jupyterも起動することからDocker環境もうまくいっているようですし、
Jupyter起動時に`Cross-validation.ipynb`などが表示されない問題は
当日パソコンを見ながら相談したほうが良いかもしれませんね。

いかがでしょうか？

**Comment by atayino** [comment]
承知致しました。ありがとうございました。

当日はよろしくお願い申し上げます。
