### ISSUE TITLE
ハンズオン環境のダウンロードについて

### ISSUE THREAD

**Issue by ghost** [chemo-wakate/tutorial-7th#9]
dockerのインストール確認、リポジトリのクローンまでは完了しましたが、ハンズオン環境のダウンロードでつまづいてしまいました。

Windows10(64bit)環境で、Windows Powershellで以下の結果が出力されました。（XXXXはユーザー名）

PS C:\Users\XXXX> cd tutorial-7th
PS C:\Users\XXXX\tutorial-7th> docker pull chemowakate/tutorial-7th
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/chemowakate/tutorial-7th/manifests/latest: unauthorized:
 incorrect username or password

初歩的な事かもしれませんが、ご教示の程宜しくお願い致します。

**Comment by yamasakih** [comment]
@T-Arima11 さん
ご質問ありがとうございます。
Docker Hubにログインする必要があると思います。

http://k28h.blogspot.jp/2017/09/macdocker.html

こちらのサイトでも同じような問題が起きて解決例を提示していますので参考にしてみてください。
`ちょと動くか試してみる(nginxが動作するか試す)`という項目のところです。

**Comment by ghost** [comment]
@yamasakih 様
早速のご返答ありがとうございました。
ご指摘の通り docker login で解決し、最後まで導入出来ました。
ブラウザでjupyterが立ち上がり、中身の資料も閲覧可能です。
当日はどうぞよろしくお願い致します。
